# Generated by Django 4.2.25 on 2025-11-29 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_guest_user_profile_service_available_to_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
